### ISSUE TITLE
Undefined instead of http/https

### ISSUE THREAD

**Issue by maguedon** [FriendsOfSymfony/FOSJsRoutingBundle#287]
Good afternoon !

I just updated FOSJsRoutingBundle and I noticed an issue with the protocol of the url generated. When I use `Routing.generate()`, the url contains "undefined" instead of "http". I have something like this : 
`"undefined://localhost/example.com"` instead of `"http://localhost/example.com"`.

In my browser console, there is this error  : `NS_ERROR_UNKNOWN_PROTOCOL:`.
When I replace the file "web\bundles\fosjsrouting\js\router.js" by the previous, it works.

I use the "dev-master" version and I'm in Symfony 2.8.

One route of my routing.yml :

``` yaml
app_editSeriepage:
    path:     /serie/{id}
    defaults: { _controller: AppBundle:Default:editSerie }
    options:
        expose: true
```

The js where I call it : 

``` js
    body.on('click', '#series tbody tr', function () {
        var id = $(this).attr('id');
        location.href = Routing.generate('app_editSeriepage', {id: id});
    });
```

Is there a specific configuration to add or is it a bug ?

Best regards,

Mathilde

**Comment by secit-pl** [comment]
The same problem here

**Comment by Belfserk** [comment]
@maguedon It helped for me to setup schemes, seems like there is a bug with them in the latest merge request.
https://symfony.com/doc/current/routing/scheme.html

**Comment by maguedon** [comment]
@Belfserk Yes it works, I will add it to all of my routes. Thanks !

**Comment by secit-pl** [comment]
@Belfserk Thanks, but this won't fix a root of the problem. The version 1.6.1 should be a non breakable update of the 1.6.0 so this is definitely a bug in jsrouting-bundle.

**Comment by VoltX** [comment]
Solved for me too, thanks for solution

Just force the routing configuration scheme
schemes:  [http] or schemes:  [https]

**Comment by Danita** [comment]
I agree with @secit-pl, this is a patch version, it should not break backwards compat. In my case, on the generated js routing I'm missing the port number as well as the protocol.

**Comment by willdurand** [comment]
> @Belfserk Thanks, but this won't fix a root of the problem. The version 1.6.1 should be a non breakable update of the 1.6.0 so this is definitely a bug in jsrouting-bundle.
>  👍 1

Agreed. That's why I could not merge the patch, no way to test it myself.

But, the new version was more than needed so I hope some of you can help @tobias-93 and @GuilhemN to fix this bug and come up with a `1.6.2` 🙏 ❤️

**Comment by tobias-93** [comment]
I'm sorry to introduce this bug for you 😒 
I've probably fixed this bug in https://github.com/tobias-93/FOSJsRoutingBundle/tree/fix-regression-1.6.1, could one of you try it?
Our infrastructure doesn't cause this bug...

**Comment by maguedon** [comment]
@tobias-93 I tried your fix and it works :)

**Comment by tobias-93** [comment]
@maguedon see #288 😄

**Comment by GuilhemN** [comment]
Hum looks like we need more tests 🤔 Sorry for releasing a broken patch but it was really needed (@tobias-93 waited more than a year). If @tobias-93 fix is correct I'll release it asap.

While there are many people here, I take this opportunity to tell you we need maintainers, I merged a few PRs but i don't know this bundle well enough to maintain it. And I don't think @stof and @willdurand have enough time (or use this bundle often enough) to do it anymore.

**Comment by NicoHaase** [comment]
So, folks, the day later the release is still broken. Wouldn't it be a solution to unpublish the broken release again, or merge the fix and publish another bugfix release, now containing real bugfixes and not only a feature one year in the making and obviously so little tested that a bug report is filed within less than two hours?

**Comment by GuilhemN** [comment]
@NicoHaase I want to be sure the fix is correct before releasing it, if you could review it, that'd help. Just stick on 1.6.0 for now, I'll release the fix today but I would be more confident with more reviews.

**Comment by SaidBeldjen** [comment]
"friendsofsymfony/jsrouting-bundle": "1.6.0",  This worked for me ! I use Symfony 2.8.

**Comment by willdurand** [comment]
Can you please try [1.6.2](https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/releases/tag/1.6.2)?

**Comment by maguedon** [comment]
The 1.6.2 works for me.

**Comment by NicoHaase** [comment]
@willdurand had it tested with one of my projects: 1.6.0 was working, 1.6.1 was broken, 1.6.2 was fine again. Thanks for releasing a fixed version 👍

**Comment by fidovo** [comment]
1.6.2 worked!

**Comment by willdurand** [comment]
Great! Hat tip to @tobias-93 and @GuilhemN!
